# Generated by Django 4.1.5 on 2023-02-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_video', models.CharField(max_length=12, unique=True)),
                ('file', models.FileField(upload_to='mp3/')),
            ],
        ),
    ]
