# Generated by Django 4.1.5 on 2023-02-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download_spotify', '0002_rename_files_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, upload_to='mp3/'),
        ),
    ]
