# Generated by Django 4.1.5 on 2023-02-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download_spotify', '0003_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='country',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='is_chart',
            field=models.BooleanField(default=False),
        ),
    ]
