# Generated by Django 4.1.5 on 2023-02-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download_spotify', '0004_file_country_file_is_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='country',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
